<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula [
        <!ELEMENT matricula (cicle, alumnes)>
        <!ELEMENT cicle (#PCDATA)>
        <!ELEMENT alumnes (alumne*)>
        <!ELEMENT alumne (nom, any, mòduls)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT any (#PCDATA)>
        <!ELEMENT mòduls (mòdul+)>
        <!ELEMENT mòdul (#PCDATA)>
        ]>
<matricula>
    <cicle>Desenvolupament d'aplicacions web</cicle>
    <alumnes>
        <alumne>
            <nom>Federicu Pi</nom>
            <any>2013</any>
            <mòduls>
                <mòdul>XML</mòdul>
                <mòdul>Programació</mòdul>
            </mòduls>
        </alumne>
        <alumne>
            <nom>Marcelinu Paivinu</nom>
            <any>2013</any>
            <mòduls>
                <mòdul>Programació</mòdul>
            </mòduls>
        </alumne>
        <alumne>
            <nom>Filomeno Garcia</nom>
            <any>2013</any>
            <mòduls>
                <mòdul>Programació</mòdul>
                <mòdul>FOL</mòdul>
            </mòduls>
        </alumne>
        <alumne>
            <nom>Eustaquio Pons</nom>
            <any>2012</any>
            <mòduls>
                <mòdul>XML</mòdul>
            </mòduls>
        </alumne>
        <alumne>
            <nom>Tomeu Bonys</nom>
            <any>2012</any>
            <mòduls>
                <mòdul>XML</mòdul>
                <mòdul>Programació</mòdul>
            </mòduls>
        </alumne>
        <alumne>
            <nom>Bernat Garengou</nom>
            <any>2013</any>
            <mòduls>
                <mòdul>XML</mòdul>
                <mòdul>Programació</mòdul>
            </mòduls>
        </alumne>
        <alumne>
            <nom>Pere Nou</nom>
            <any>2013</any>
            <mòduls>
                <mòdul>Programació</mòdul>
            </mòduls>
        </alumne>
        <alumne>
            <nom>Bill Garcia</nom>
            <any>2013</any>
            <mòduls>
                <mòdul>XML</mòdul>
                <mòdul>Programació</mòdul>
                <mòdul>FOL</mòdul>
            </mòduls>
        </alumne>
    </alumnes>
</matricula>